---
date: ' 2020-03-18T10:54:24 '
draft: false
linktitle: Lab 11
menu: 
     MES623Econ:
          parent: Lab Material
          weight: 11
title:  Regulation Mechanisms and the Equimarginal Principle
type: docs
weight: 11
output:
  blogdown::html_page:
    toc: true
---


<div id="TOC">
<ul>
<li><a href="#creating-marginal-cost-functions">Creating Marginal Cost Functions</a></li>
<li><a href="#creating-demand-curves">Creating Demand Curves</a></li>
<li><a href="#abatement-regulation-a-cap">Abatement Regulation: A Cap</a></li>
<li><a href="#abatement-regulation-tax">Abatement Regulation: Tax</a></li>
<li><a href="#abatement-regulation-cap-and-trade">Abatement Regulation: Cap and Trade</a></li>
</ul>
</div>

<p>In today’s lab, we explore pollution regulations in terms of caps and taxes, under the equimarginal principle.</p>
<p>If we can recall from lecture (lecture 8), the <strong>equimarginal principle</strong> states that the costs of pollution control are minimized when the marginal costs of abatement are equalized across sources.</p>
<div class="figure"><span id="fig:unnamed-chunk-1"></span>
<img src="/images/MES623_Lab11_EP_picture.png" alt="Equimarginal Principle"  />
<p class="caption">
Figure 1: Equimarginal Principle
</p>
</div>
<p>Given the graphic we have two sources of pollution, the optimal price per additional unit of abatement is the same for each source. The optimal level of abatement is different for each source at that price.</p>
<p><strong>For 3 different sources of pollution, we are given information on levels of abatement, and their marginal Cost.</strong> Download the data <a href="/files/MES623_Lab11_lab_data.csv">here</a>.</p>
<p>Let’s read in the data:</p>
<pre class="r"><code>Data = read.csv(&quot;MES623_Lab11_lab_data.csv&quot;)</code></pre>
<div id="creating-marginal-cost-functions" class="section level3">
<h3>Creating Marginal Cost Functions</h3>
<p>Now, let’s determine a model/functional form for the marginal cost of abatement for each of the different sources. First, look at your data in a plot:</p>
<pre class="r"><code>#Source A
plot(Data$Abatement, Data$MC_A, pch = 16, cex = 1.3, col = &quot;blue&quot;,
          main = &quot;Marginal cost of abatement of Source A&quot;,
     xlab = &quot;Abatement&quot;, ylab = &quot;Marginal cost&quot;) </code></pre>
<p><img src="/teaching/MES623Econ/Lab_11_Regulation_Mechanisms_files/figure-html/unnamed-chunk-3-1.png" width="672" />
It looks like a straight line should work so our functional form, where the intercept can be estimated by R. Our model should look like something like this: <span class="math display">\[Y=\alpha+\beta X\]</span>, where <span class="math inline">\(X\)</span> is the level of abatement. Let’s try this in a basic linear model.</p>
<pre class="r"><code># Model for Source A
Model_A &lt;- lm(Data$MC_A~Data$Abatement)
summary(Model_A)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Data$MC_A ~ Data$Abatement)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -41.593 -11.185  -2.643  10.641  35.552 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     -4.2447    10.1849  -0.417 0.683172    
## Data$Abatement   0.5970     0.1157   5.160 0.000145 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.33 on 14 degrees of freedom
## Multiple R-squared:  0.6554, Adjusted R-squared:  0.6308 
## F-statistic: 26.62 on 1 and 14 DF,  p-value: 0.0001448</code></pre>
<pre class="r"><code># Original Plot of Source A data (run these lines all at one time)
plot(Data$Abatement, Data$MC_A, pch = 16, cex = 1.3, col = &quot;blue&quot;,
      main = &quot;Marginal cost of abatement of Sector A&quot;,
     xlab = &quot;Abatement&quot;, ylab = &quot;Marginal cost&quot;)
lines(Data$Abatement,predict(Model_A)) # Plot the predicted Marginal cost given the model</code></pre>
<p><img src="/teaching/MES623Econ/Lab_11_Regulation_Mechanisms_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Another way to check to see if this model works is by checking the r.squared values. Remember our definitions from lab 8:</p>
<p><strong>R-squared</strong> - A measure of the linear relationship between the <span class="math inline">\(X\)</span> and the <span class="math inline">\(Y\)</span> variables. Stays between 0 and 1: 0 - the model does not explain the variance in the response variable; 1 - the model explains the variance in the response variable.</p>
<pre class="r"><code>summary(Model_A)$r.squared</code></pre>
<pre><code>## [1] 0.6553822</code></pre>
<pre class="r"><code>summary(Model_A)$adj.r.squared</code></pre>
<pre><code>## [1] 0.6307666</code></pre>
<p>Our results show that 65.5 % of the variance is being explained by our model. This is greater than 50% so we should be OK to use this as our functional form. But let’s try forcing the intercept to be zero and see if we get a better R-squared values.</p>
<pre class="r"><code>Model_A &lt;- lm(Data$MC_A~0+Data$Abatement)
summary(Model_A)$r.squared</code></pre>
<pre><code>## [1] 0.8559175</code></pre>
<pre class="r"><code>summary(Model_A)$adj.r.squared</code></pre>
<pre><code>## [1] 0.846312</code></pre>
<p>This improved our values so we will use the newer model as our functional form.</p>
<p>Let’s try this same functional form for Source B:</p>
<pre class="r"><code># Source B
Model_B &lt;- lm(Data$MC_B~0+Data$Abatement)
summary(Model_B)$r.squared</code></pre>
<pre><code>## [1] 0.8106292</code></pre>
<pre class="r"><code>summary(Model_B)$adj.r.squared</code></pre>
<pre><code>## [1] 0.7980045</code></pre>
<p>Our R squared is pretty OK. Let’s take a look at the plot of the observed and predicted data.</p>
<pre class="r"><code>plot(Data$Abatement, Data$MC_B, pch = 16, cex = 1.3, col = &quot;blue&quot;, 
      main = &quot;Marginal cost of abatement of Source B&quot;,
     xlab = &quot;Abatement&quot;, ylab = &quot;Marginal cost&quot;)
lines(Data$Abatement,predict(Model_B))</code></pre>
<p><img src="/teaching/MES623Econ/Lab_11_Regulation_Mechanisms_files/figure-html/unnamed-chunk-8-1.png" width="672" />
Looks good to me!</p>
<p>Let’s do the same thing for our last source of pollution, source c.</p>
<pre class="r"><code>Model_C&lt;- lm(Data$MC_C~0+Data$Abatement)
summary(Model_C)$r.squared</code></pre>
<pre><code>## [1] 0.9076426</code></pre>
<pre class="r"><code>summary(Model_C)$adj.r.squared</code></pre>
<pre><code>## [1] 0.9014855</code></pre>
<pre class="r"><code>plot(Data$Abatement, Data$MC_C, pch = 16, cex = 1.3, col = &quot;blue&quot;, main = &quot;Marginal cost of abatement of Source C&quot;, 
     xlab = &quot;Abatement&quot;, ylab = &quot;Marginal cost&quot;)
lines(Data$Abatement,predict(Model_C))</code></pre>
<p><img src="/teaching/MES623Econ/Lab_11_Regulation_Mechanisms_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This is OK, but it looks like there are a good proportion of the points in the middle abatement range that are below the line. Maybe we need a curved line? To do this we can make the relationship with abatement quadratic rather than linear. In the code below we use the I() operator around the squared abatement term to tell R that this is a part of the linear regression not a separate operation in the formula. Try running the linear model without <code>I()</code> and see what you get.</p>
<pre class="r"><code>Model_C &lt;- lm(Data$MC_C~0+Data$Abatement+I(Data$Abatement^2))
summary(Model_C)$r.squared</code></pre>
<pre><code>## [1] 0.9345342</code></pre>
<pre class="r"><code>summary(Model_C)$adj.r.squared</code></pre>
<pre><code>## [1] 0.925182</code></pre>
<pre class="r"><code>plot(Data$Abatement, Data$MC_C, pch = 16, cex = 1.3, col = &quot;blue&quot;, 
       main = &quot;Marginal cost of abatement of source C&quot;, 
     xlab = &quot;Abatement&quot;, ylab = &quot;Marginal cost&quot;)
lines(Data$Abatement,predict(Model_C))</code></pre>
<p><img src="/teaching/MES623Econ/Lab_11_Regulation_Mechanisms_files/figure-html/unnamed-chunk-10-1.png" width="672" />
Our R-squared values went up and the graph doesn’t look too bad!</p>
<p>We now have three models for marginal cost, two are linear and one is quadratic. As in previous labs we can extract the coefficients from each model using R code similar to <code>Model_C$coefficients[1]</code>.</p>
</div>
<div id="creating-demand-curves" class="section level3">
<h3>Creating Demand Curves</h3>
<p>Let’s deal with the linear models first. The marginal cost of abatement from source <span class="math inline">\(i\)</span> is given by <span class="math inline">\(MC_i=a_i+b_iA_i\)</span>, where <span class="math inline">\(a_i\)</span> and <span class="math inline">\(b_i\)</span> are the intercept and the slope estimated in the regression analysis, respectively. In our case the intercept is forced to be zero. When the current level of emissions is <span class="math inline">\(A^0_i\)</span>, then the demand for carbon emissions is given by <span class="math inline">\(P_i=(a_i+b_iA^0_i)-b_iQ_i\)</span>; where <span class="math inline">\(Q_i\)</span> is an amount of carbon in tons. Let’s say the current levels of emissions for source A and B are 160 and 220 respectively.To get a full demand curve we want to calculate the demand for each <span class="math inline">\(Q\)</span> between zero and the current level of emissions.</p>
<pre class="r"><code># Our current level of emissions saved as an object
Qt_A = 220
Qt_B = 160

# Demand for source A
# Remember we don&#39;t have an intercept, just a coefficient for abatement.
# This means the alpha term from the equation above goes away.
D_A = (Model_A$coefficients[1]*Qt_A)-Model_A$coefficients[1]*seq(0,Qt_A,1) 
# seq() generating a sequence of Qs for this calculation

# Demand for source B
D_B = (Model_B$coefficients[1]*Qt_B)-Model_B$coefficients[1]*seq(0,Qt_B,1)</code></pre>
<p>Now, source C is similar but with the quadratic model. If the marginal cost is given by <span class="math inline">\(MC_i=a_i+b_iA_i+c_iA^2_i\)</span>, the demand curve is given by <span class="math inline">\(P_i=b_i(A^0_i-Q_i)+c_i(A^0_i-Q_i)^2\)</span> where the intercept is zero. Again, the current level of emissions is <span class="math inline">\(A^0_i\)</span> which is 400 for source C.</p>
<pre class="r"><code># Our current level of emissions saved as an object
Qt_C = 240

D_C &lt;- Model_C$coefficients[1]*(Qt_C-seq(0,Qt_C,1))+Model_C$coefficients[2]*(Qt_C-seq(0,Qt_C,1))^2</code></pre>
<p>Let’s graph these demand curves. Which pollution source is willing to pay the most for the first unit of carbon emissions?</p>
<pre class="r"><code>plot(c(0,300),c(0,300), type=&quot;n&quot;, xlab=&quot;Emissions&quot;, ylab=&quot;Price&quot;, main=&quot;Demand for Emissions&quot;)
lines(seq(0,Qt_A,1),D_A,lwd=2)
lines(seq(0,Qt_B,1),D_B,col=&quot;red&quot;,lwd=2)
lines(seq(0,Qt_C,1),D_C,col=&quot;green&quot;,lwd=2)
legend(&quot;topright&quot;,legend=c(&quot;Source A&quot;,&quot;Source B&quot;,&quot;Source C&quot;),
        col=c(&quot;black&quot;,&quot;red&quot;,&quot;green&quot;), lty=c(1,1,1), cex=0.8)</code></pre>
<p><img src="/teaching/MES623Econ/Lab_11_Regulation_Mechanisms_files/figure-html/unnamed-chunk-13-1.png" width="672" />
It seems that Source C (green) is the one willing to pay the most of for the first unit of emission.</p>
</div>
<div id="abatement-regulation-a-cap" class="section level3">
<h3>Abatement Regulation: A Cap</h3>
<p>Pollution sources A and C are the pollution sources for country Z, and their regulation states that there must be a cap on carbon emissons. They must cut their emissions by a fourth of their current emissions (reducing total emissions from 460 to 345). There will be no local pollutants affected by the carbon abatement so we do not have to worry about co-benefits. What is the total cost of following this regulation, as well as the cost of abatement and pollution for each source?</p>
<p>First, we have to remember that to get from marginal values to totals, we need to calculate the area below the marginal curve. We typically just take the area of a triangle below the curve but we can do this another way. We can calculate an integral, where the area below a straight line, <span class="math inline">\(y=a+bx\)</span>, between two arbitrary points, <span class="math inline">\(x_0\)</span> and <span class="math inline">\(x_1\)</span>, is given by:</p>
<p><span class="math display">\[\int_{x_0}^{x_1}a+bx\;dx=ax+\frac{b}{2}x^2+C\;\Bigg\vert^{x_1}_{x_0}=a(x_1-x_0)+\frac{b}{2}(x_1^2-x_0^2)\]</span>
If you don’t remember integrals it’s OK. Just remember that if you are taking an integral with respects to a certain variable such as <span class="math inline">\(X\)</span>, you just increase the power of the variable and divide by that power. For instance, the integral of the constant <span class="math inline">\(a\)</span> is <span class="math inline">\(ax\)</span>. We added an <span class="math inline">\(X^1/1\)</span> to our constant giving us <span class="math inline">\(ax\)</span>. We do this for each term in the equation and then evaluate the equation at <span class="math inline">\(x_1\)</span> and subtract the same equation evaluated at <span class="math inline">\(x_0\)</span>.</p>
<p>For the quadratic marginal cost function, <span class="math inline">\(y=bx+cx^2\)</span>, we do the same thing:</p>
<p><span class="math display">\[\int_{x_0}^{x_1}bx+cx^2\;dx=\frac{b}{2}x^2+\frac{c}{3}x^3+C\;\Bigg\vert^{x_1}_{x_0}=\frac{b}{2}(x_1^2-x_0^2)+\frac{c}{3}(x_1^3-x_0^3)\]</span></p>
<p>Given our new equations for area we can estimate the total cost of abating a fourth of their units in each sector, where <span class="math inline">\(x_0=0\)</span> and <span class="math inline">\(x_1=Q_t/4\)</span> where Qt changes based on the pollution source. Let’s create some functions to do this for us.</p>
<pre class="r"><code>linear.cost &lt;- function(x0,x1,b) 
  # the function will take the values for the units of abatement and the coefficient
  # remember there is only one coefficient since we forced the intercept to be zero
  # you may need two coefficients for your homework
  {
  as.numeric(b/2*(x1^2-x0^2)) # here is the equation for the integral of the linear function
  }

quadratic.cost &lt;- function(x0,x1,b,c) # same as the linear function
  { 
  as.numeric(b/2*(x1^2-x0^2)+c/3*(x1^3-x0^3)) # the integral of the quadratic function
  }

# Total cost for Source A
C4_A &lt;- linear.cost(0,(Qt_A/4),Model_A$coefficients[1])
C4_A</code></pre>
<pre><code>## [1] 840.7795</code></pre>
<pre class="r"><code># Total cost for Source C
C4_C &lt;- quadratic.cost(0,(Qt_C/4),Model_C$coefficients[1],Model_C$coefficients[2])
C4_C</code></pre>
<pre><code>## [1] 1104.678</code></pre>
<pre class="r"><code># Total cost
C4_A+C4_C</code></pre>
<pre><code>## [1] 1945.457</code></pre>
</div>
<div id="abatement-regulation-tax" class="section level3">
<h3>Abatement Regulation: Tax</h3>
<p>To emit a ton of carbon in country Z, you must pay a tax of <span class="math inline">\(t\)</span> per unit of carbon emitted. Again let’s find the total cost of abatement and the cost of abatement and pollution for each source of pollution.</p>
<p>First we will need to find the minimum tax that allows us to reduce total emissions by 1/4 (from 460 to 345). Does this sound familiar?</p>
<p>Yes, we must invoke the equimarginal principle! We need to find the optimal allocation of units that minimizes the total cost of abating 115 units. Basically, all sources will abate until their marginal cost of abatement is equal, and the total abatement is 115.</p>
<p>We need an optimization function that minimizes total cost by adjusting the number of units abated between source A and C. The units abated between sources have to add to 115 but can be distributed across sources in many ways. We will use the library <code>Rsolnp</code> for this.</p>
<pre class="r"><code># Load the optimizing library
library(Rsolnp)</code></pre>
<pre><code>## Warning: package &#39;Rsolnp&#39; was built under R version 3.6.3</code></pre>
<p>Let’s think about how we will set up our optimization. Recall the previous labs. Here is the format:</p>
<pre class="r"><code>OO &lt;- solnp( X,# Starting values
      fun =  # Function to minimize
      eqfun = # Total abatement achieved
      eqB = # Total abatement goal
      LB =  # Lower bound for decision variables, must be a vector 
      UB = # Upper bound for decision variables, must be a vector as well)</code></pre>
<p>Let’s start filling things in.</p>
<pre class="r"><code># Total cost funtion to be minimized
tot.cost = function(X){ # X is a vector of two abatement values, one for source A and one for source C
  
  # Total cost for Source A
  Cost_A = linear.cost(0,X[1],Model_A$coefficients[1]) # X[1] is the units of abatement for source A
 
   # Total cost for source C
  Cost_C = quadratic.cost(0,X[2],Model_C$coefficients[1],Model_C$coefficients[2])
  
  # Total cost
  TC &lt;- Cost_A+Cost_C
  TC
}

# The total abatement has to be 1/4 of the total which is 115
# Function that calculates total abatement
tot.abatement &lt;- function(X)
  { 
  TA &lt;- sum(X) # Sum of the vector of values of abatement
  TA
}

X &lt;- rep(0.1,2) # Create a set of starting values different than zero.

OO &lt;- solnp(X, # Starting values
      fun = tot.cost, # Function to minimize
      eqfun = tot.abatement, # Total abatement achieved
      eqB = 115, # Total abatement goal
      LB = rep(0,2), # Lower bound for decision variables, must be a vector 
      UB = c(Qt_A,Qt_C)) # Upper bound for decision variables, must be a vector as well</code></pre>
<pre><code>## 
## Iter: 1 fn: 1887.3332     Pars:  63.52040 51.47960
## Iter: 2 fn: 1887.3330     Pars:  63.52040 51.47960
## Iter: 3 fn: 1887.3330     Pars:  63.52040 51.47960
## solnp--&gt; Completed in 3 iterations</code></pre>
<pre class="r"><code>X &lt;- OO$pars # extract the level of abatement at the optimal price for both sources
X</code></pre>
<pre><code>## [1] 63.5204 51.4796</code></pre>
<p>Notice the two values in the X vector sum to 115, so that part worked.</p>
<p>Given the equimarginal principle, the optimal tax is equal to the marginal cost of abatement at equilibrium. If the theory is right, that means that at the optimal solution, all marginal costs of abatement should be the same. Let’s check that prediction:</p>
<pre class="r"><code># Source A
opt.MC_A= Model_A$coefficients[1]*X[1]
opt.MC_A</code></pre>
<pre><code>## Data$Abatement 
##       35.31018</code></pre>
<pre class="r"><code># Source C
opt.MC_C=Model_C$coefficients[1]*X[2]+Model_C$coefficients[2]*X[2]^2
opt.MC_C</code></pre>
<pre><code>## Data$Abatement 
##       35.31018</code></pre>
<p>It worked! The optimal tax is <span class="math inline">\(t^*=35.31\)</span>.</p>
<p>What was the total cost of abatement? We can use our <code>tot.cost</code> function to figure this out. It has the integral within it.</p>
<pre class="r"><code>tot.cost(X)</code></pre>
<pre><code>## [1] 1887.333</code></pre>
<p>What is the cost of abatement for each source? Use the individual integral functions.</p>
<pre class="r"><code># Cost of abating for Source A
as.numeric(linear.cost(0,X[1],Model_A$coefficients[1]))</code></pre>
<pre><code>## [1] 1121.458</code></pre>
<pre class="r"><code># Cost of abating for Source C
as.numeric(quadratic.cost(0,X[2],Model_C$coefficients[1],Model_C$coefficients[2]))</code></pre>
<pre><code>## [1] 765.8746</code></pre>
<p>What is the cost of pollution for each source? Units of carbon emission that are above the optimal units of abatement are taxed.</p>
<pre class="r"><code>tax = opt.MC_C 
# Cost of polluting for source A
# any units from the point of abatement to the current emissions level, are taxed
as.numeric((Qt_A-X[1])*tax) </code></pre>
<pre><code>## [1] 5525.323</code></pre>
<pre class="r"><code># Cost of polluting for Source C
as.numeric((Qt_C-X[2])*tax)</code></pre>
<pre><code>## [1] 6656.69</code></pre>
</div>
<div id="abatement-regulation-cap-and-trade" class="section level3">
<h3>Abatement Regulation: Cap and Trade</h3>
<p>We will pick up here next week. What would the total cost be if we not only had a cap of 1/4 of total emissions but the two sources were also allowed to trade?</p>
<p>To Be Continued …</p>
</div>
